
export const predefinedTags = [
  { label: "Mental health", value: "Mental health" },
  { label: "Child mental health", value: "Child mental health" },
  { label: "Latest development", value: "Latest development" },
  { label: "Mental health news", value: "Mental health news" },
  { label: "Adult mental health", value: "Adult mental health" },
  { label: "Geriatric psychiatry", value: "Geriatric psychiatry" },
  { label: "Sexual health", value: "Sexual health" },
  { label: "Emotional health", value: "Emotional health" },
  { label: "Adolescent mental health", value: "Adolescent mental health" },
  { label: "Couple counseling", value: "Couple counseling" },
  { label: "Substance abuse", value: "Substance abuse" },
  { label: "Addiction", value: "Addiction" },
  { label: "Preventive mental health", value: "Preventive mental health" },
  { label: "Psychology", value: "Psychology" },
  { label: "Neuropsychiatry", value: "Neuropsychiatry" },
  { label: "School mental health", value: "School mental health" },
  { label: "Corporate mental health", value: "Corporate mental health" },
  { label: "Success story", value: "Success story" },
  { label: "IPS news", value: "IPS news" },
  { label: "Patient story", value: "Patient story" },
  { label: "Stories of hope", value: "Stories of hope" },
  { label: "Workplace mental health", value: "Workplace mental health" },
  { label: "Research", value: "Research" },
  { label: "Academics", value: "Academics" },
  { label: "Positivity", value: "Positivity" },
];
